# Generated by Django 5.1.4 on 2024-12-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_options_producto_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(default='Sin fabricante', max_length=100),
        ),
    ]
