# Generated by Django 5.1.4 on 2024-12-27 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.fabricante'),
        ),
    ]
