# Generated by Django 5.1.4 on 2024-12-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCombustible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="modelocarro",
            name="tipo_combustible",
            field=models.ManyToManyField(
                related_name="modelo_carros", to="relaciones.tipocombustible"
            ),
        ),
    ]
