# Generated by Django 5.1.4 on 2024-12-24 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relaciones", "0002_tipocombustible_modelocarro_tipo_combustible"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectorEjecutivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255)),
                (
                    "automotriz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relaciones.automotriz",
                    ),
                ),
            ],
        ),
    ]
