# Generated by Django 5.1.4 on 2024-12-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migraciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preciohistoricovehiculos",
            name="color",
            field=models.CharField(default="Desconocido", max_length=120),
        ),
        migrations.AlterField(
            model_name="preciohistoricovehiculos",
            name="modelo",
            field=models.TextField(),
        ),
    ]
