# Generated by Django 5.1.4 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migraciones", "0002_preciohistoricovehiculos_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciohistoricovehiculos",
            name="color",
            field=models.CharField(default="Desconocido", max_length=50),
        ),
    ]
