# Generated by Django 5.1.4 on 2024-12-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_fabricante_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricante',
            name='pais',
        ),
        migrations.AddField(
            model_name='producto',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
