# Generated by Django 5.1.4 on 2024-12-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_fabricante_pais_producto_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
