# Generated by Django 5.1.4 on 2024-12-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_fabricante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.fabricante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
